# Generated by Django 4.2.4 on 2023-11-13 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_image', models.ImageField(upload_to='products')),
                ('product_price', models.FloatField()),
                ('product_old_price', models.FloatField()),
                ('product_brand', models.CharField(max_length=50)),
                ('product_discription', models.TextField()),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_categories.product_categories')),
            ],
        ),
    ]
